### ISSUE TITLE
release time

### ISSUE THREAD

**Issue by alonek1** [fransr/postMessage-tracker#1]
you've told you'll release it in one week in LA live video, but ... :)

**Comment by attacker420** [comment]
:(

**Comment by sandeepl337** [comment]
Seems he didn't released thetool :) ###

**Comment by fransr** [comment]
Now it is!

**Comment by eligrey** [comment]
@fransr Any reason you didn't publish to the Chrome Web Store? Is it just a matter of creating the required image assets?
